import type { Metadata } from "next";
import { Header } from "@/components/header"
import "./globals.css";

export const metadata: Metadata = {
  title: "Mikuru Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        <Header />
        <div className="container mx-auto px-4 pb-8 sm:px-6 lg:px-8">
          {children}
        </div>
      </body>
    </html>
  );
}
